# Spring Boot Configuration
spring:
  application:
    name: nukkadseva-backend

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Database Configuration
  datasource:
    url: jdbc:postgresql://db.nuziesuojsthsqohsoah.supabase.co:5432/postgres
    username: postgres
    password: "7kYQ/D8meR2@w&D"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    azure:
      storage:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
        blob:
          container-name: ${AZURE_BLOB_CONTAINER_NAME:nukkadseva-files}

  # Liquibase Configuration
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.json
    default-schema: public
    contexts: dev
    drop-first: false
    clear-checksums: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}

# Storage Configuration
storage:
  type: local  # Use 'azure' for production, 'local' for development

# Server Configuration
server:
  port: 8080
  address: 0.0.0.0

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
#    org.hibernate: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    expiration: 86400000

app:
  # Change this base-url to your server's IP (e.g., http://10.38.28.45:8080) for email verification links
  base-url: ${APP_BASE_URL:http://localhost:8080}

  #  datasource:
  #    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
  #    username: postgres.onaepeojtpyopiovfkal
  #    password: g!ZEC8ME.W.W_Ae
  #    driver-class-name: org.postgresql.Driver
  # JPA Configuration
