# Spring Boot Configuration
spring:
  application:
    name: nukkadseva-backend


  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/nukkadseva
    username: postgres
    password: yusuf@123

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    azure:
      storage:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
        blob:
          container-name: ${AZURE_BLOB_CONTAINER_NAME:nukkadseva-files}

  # Liquibase Configuration
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.json
    default-schema: public
    contexts: dev
    drop-first: false
    clear-checksums: true

# Storage Configuration
storage:
  type: local  # Use 'azure' for production, 'local' for development

# Server Configuration
server:
  port: 8080

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
#    org.hibernate: DEBUG

jwt:
  secret:
    key: bHVra2Fkc2V2YS1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24tYW5kLWF1dGhvcml6YXRpb24=
    expiration: 86400000

  #  datasource:
  #    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
  #    username: postgres.onaepeojtpyopiovfkal
  #    password: g!ZEC8ME.W.W_Ae
  #    driver-class-name: org.postgresql.Driver
  # JPA Configuration