spring:
  application:
    name: nukkadseva-backend

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa: {}

  cloud:
    azure:
      storage:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
        blob:
          container-name: ${AZURE_BLOB_CONTAINER_NAME:nukkadseva-files}

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.json
    default-schema: public
    drop-first: false
    clear-checksums: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}

# Server Configuration
server:
  port: 8080
  address: 0.0.0.0

# JWT Configuration
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    expiration: 86400000

# Google OAuth
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

# App Configuration
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

# Default profile: dev
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:prod}
