
# Spring Boot Configuration
spring:
  application:
    name: nukkadseva-backend


  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/nukkadseva
    username: "postgres"
    password: "yusuf@123"
#  datasource:
#    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
#    username: postgres.onaepeojtpyopiovfkal
#    password: g!ZEC8ME.W.W_Ae
#    driver-class-name: org.postgresql.Driver
  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true

  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.json
    default-schema: public
    contexts: dev
    # Set to true to drop all database objects before running migrations (use with caution in production!)
    drop-first: false
    # Set to true to clear all checksums in the current log (useful for development)
    clear-checksums: false

  # Server Configuration
  server:
    port: 8080

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springdoc: DEBUG

jwt:
  secret:
    key: bHVra2Fkc2V2YS1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24tYW5kLWF1dGhvcml6YXRpb24=
